export enum AriaLabel {
  Burger = 'Бургер-меню',
  CalculationModule = 'Модуль калькуляції',
  CloseButton = 'Кнопка закриття',
  CloseMenu = 'Закрити меню',
  CloseModal = 'Закриття модалки',
  Collapse = 'Згорнути зміст',
  ComeBack = 'Повернення на Головну',
  Email = 'Пошта',
  Expand = 'Розгорнути зміст',
  FooterNav = 'Навігація футера',
  Logo = 'Логотип',
  Navigation = 'Основне меню',
  OpenMenu = 'Відкрити меню',
  Phone = 'Телефон',
  Range = 'Відсоток унікальності',
  ScrollArrow = 'Стрілка доверху',
  ScrollUp = 'Скрол доверху',
  SwitchTheme = 'Перемкнення теми',
  Telegram = 'Телеграм',
  Theme = 'Кольорова тема',
}

export enum DropdownAriaId {
  WORK_TYPE = 'work-type',
  EXPERTISE_AREA = 'expertise-area',
  EXECUTION_TIME = 'execution-time',
}

export enum AriaId {
  Accession = 'accession',
  AccessionProcedure = 'accession-procedure',
  CalculationModule = 'calculation-module',
  ComeBack404 = 'come-back-page',
  ComeHome = 'come-home',
  ComplexOrdering = 'complex-ordering',
  CostOutput = 'cost-output-button',
  DefaultOrdering = 'default-ordering',
  DefaultPromotionsOrdering = 'default-promotions-ordering',
  Performers = 'performers-page',
  Policy = 'policy',
  Service = 'services',
  ThemeInput = 'theme-description',
}

export enum AriaDescription {
  Accession = 'Це посилання з ознайомчої секції на офіційний Telegram-бот, де ви зможете заповнити необхідні поля і приєднатися до команди виконавців.',
  AccessionProcedure = 'Це посилання на офіційний Telegram-бот, де ви зможете заповнити необхідні поля і приєднатися до команди виконавців.',
  CalculationModule = 'Кнопка відкриття модулю калькуляції вартості роботи',
  ComeBack404 = 'Ця кнопка поверне вас на попередню сторінку',
  ComeHome = 'Перехід на головну сторінку, або скрол доверху сторінки, якщо поточна сторінка є головною',
  ComplexOrdering = 'Перехід в телеграм-бот зі збереженням введених попередньо даними в модулі розрахунку вартості',
  CostOutput = 'Кнопка виведення результатів розрахунку вартості роботи згідно з введеними даними',
  DefaultOrdering = 'Кнопка переходу  з ознайомчої секції до Telegram-боту для оформленння замовлення',
  DefaultPromotionsOrdering = 'Кнопка переходу з секції Акції до Telegram-боту для оформленння замовлення',
  Performers = 'Кнопка для переходу на сторінку для виконавців',
  Policy = 'Посилання переходу на сторінку Політики конфіденційності',
  Service = 'Посилання на телеграм-бот для замовлення типа послуг',
  ThemeInput = 'В цьому полі ви можете ввести тему вашої роботи. Зверніть увагу, що це поле не є обов`язковим для розрахунку вартості вашої роботи',
}
