name: deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lazlovalentin008
          password: keVmqr131

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: lazlovalentin008/atlasnext:2
          file: Dockerfile

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Оновлення дев гілки на сервері 
        run: |
          docker compose stop
          docker rm nextjs
          docker rmi ${{secrets.DOCKERHUB_USERNAME}}/atlasnext:2
          docker compose up -d
