name: Run Tests and Publish Allure Report 1

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests with Allure
        run: npm run test
        continue-on-error: true
      
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  upload-results:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Setup Allure
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
